---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: online-boutique
  namespace: gitops
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: main
  path: ./online-boutique
  prune: true